### PR TITLE
Integration fixes

### LINKED ISSUE #6: RapidPro API error
We are receiving this error back from RapidPro:

```
{\"non_field_errors\":[\"Parameter groups is deprecated and can't be used together with group_uuids\"]}
```

### PR DESCRIPTION
**Pull request by rcrichton**
Closes #6 and more. See each commit for more information on each fix.

@hnnesv please can you review this? Sorry, it's out of sprint...

### CODE REVIEW

**Comment by rcrichton** [comment]
The changes may make more sense if you review this individual commits.

**Comment by hnnesv** [comment]
Looks good to me 👍  Cool yeah it made sense when read them in individual commits

(i see travis is still waiting to get started - will wait before merging)

**Comment by rcrichton** [comment]
Cool. Travis seems to be taking really long time to start building this... I see one of the test was able to be run at least.

**Comment by hnnesv** [comment]
aah there we go

**Pull request merged**
